project:
  type: book

book:
  title: "BI documentation"
  author: "Sebastian Sosa"
  date: "09/09/2024"
  chapters:
    - index.qmd
    - 0. Introduction.qmd
    - 1. Linear Regression for continuous variable.qmd
    - 2. Multiple continuous Variables.qmd
    - 3. Interaction between continuous variables.qmd
    - 4. Categorical variable.qmd
    - 5. Binomial model.qmd
    - 6. Beta binomial model.qmd
    - 7. Poisson model.qmd
    - 8. Gamma-Poisson.qmd
    - 9. Multinomial model.qmd
    - 10. Dirichlet model (wip).qmd
    - 11. Zero inflated (wip).qmd
    - 12. Varying interceps.qmd
    - 13. Varying slopes.qmd
    - 14. Multiple varying slopes.qmd
    - 15. Continuous varying slopes.qmd
    - 16. Gaussian processes.qmd
    - 17. Measuring error (wip).qmd
    - 18. Missing data (wip).qmd
    - 19. Network model.qmd
    - 19.1. Sender receiver network model.qmd
    - 19.2. Block model network.qmd
    - 20. Multiplex network model.qmd
    - 21. Multiplex temporal network model.qmd
    - 22. Multilayer network model.qmd


bibliography: references.bib

format: live-html

pyodide:
  packages:
    - jaxlib==0.4.25+cpu 
    - jax==0.4.25


