project:
  type: book

book:
  title: "BI documentation"
  author: "Sebastian Sosa"
  date: "09/09/2024"
  repo-url: https://github.com/BGN-for-ASNA/ASNA_reliability
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  cover-image: cover.png

  chapters:
    - index.qmd
    - 0. Introduction.qmd
    - 1. Linear Regression for continuous variable.qmd
    - 2. Multiple continuous Variables.qmd
    - 3. Interaction between continuous variables.qmd
    - 4. Categorical variable.qmd
    - 5. Binomial model.qmd
    - 6. Beta binomial model.qmd
    - 7. Poisson model.qmd
    - 8. Gamma-Poisson.qmd
    - 9. Multinomial model.qmd
    - 10. Dirichlet model (wip).qmd
    - 11. Zero inflated.qmd
    - 12. Survival analysis.qmd
    - 13. Varying intercepts.qmd
    - 14. Varying slopes.qmd
    - 15. Gaussian processes.qmd
    - 16. Measuring error.qmd
    - 17. Missing data (wip).qmd
    - 18. Latent variable (wip).qmd
    - 19. PCA.qmd
    - 20. Network model.qmd
    - 21. Network with block model.qmd 
    - 22. Network control for data collection biases (wip).qmd
    - 23. Network Metrics.qmd
    - 24. Network Based Diffusion analysis (wip).qmd



bibliography: references.bib

format:
  html:
    theme: Morph
    backgroundcolor: "#ffffff"
    code-copy: true
    highlight-style: monokai
    include-after-body: tooltip-scripts.html
  pdf: default



