project:
  type: book

book:
  title: "BI documentation"
  author: "Sebastian Sosa"
  date: "09/09/2024"
  chapters:
    - index.qmd
    - 0. Introduction.qmd
    - 1. Linear Regression for continuous variable.qmd
    - 2. Multiple continuous Variables.qmd
    - 3. Interaction between continuous variables.qmd
    - 4. Categorical variable.qmd
    - 5. Binomial model.qmd
    - 6. Beta binomial model.qmd
    - 7. Poisson model.qmd
    - 8. Gamma-Poisson.qmd
    - 9. Multinomial model.qmd
    - 10. Dirichlet model (wip).qmd
    - 11. Zero inflated (wip).qmd
    - 12. Varying intercepts.qmd
    - 13. Varying slopes.qmd
    - 14. Gaussian processes (wip).qmd
    - 15. Measuring error (wip).qmd
    - 16. Missing data (wip).qmd
    - 17. Latent variable (wip).qmd
    - 18. Network model.qmd
    - 19. Network with block model.qmd 
    - 20. Network control for data collection biases (wip).qmd
    - 21. Network Metrics (wip).qmd
    - 22. Multilayer network model (wip).qmd
    - 23. Multiplex temporal network model (wip).qmd
    - 24. Multiplex network model (wip).qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
  pdf: default



