project:
  type: book

book:
  title: "BI documentation"
  author: "Sebastian Sosa"
  date: "09/09/2024"
  chapters:
    - index.qmd
    - 0. Introduction.qmd
    - 1. Linear Regression for continuous variable.qmd
    - 2. Multiple continuous Variables.qmd
    - 3. Interaction between continuous variables.qmd
    - 4. Categorical variable.qmd
    - 5. Binomial regression.qmd
    - 6. Poisson regression.qmd
    - 7. Negative binomial.qmd
    - 8. Multinomial.qmd
    - 9. Beta binomial.qmd
    - 10. Negative-binomial.qmd
    - 11. Zero inflated.qmd
    - 12. Varying interceps.qmd
    - 13. Varying slopes.qmd
    - 14. Multiple varying slopes.qmd
    - 15. Continuous varying slopes.qmd
    - 16. Gaussian processes.qmd    
    - 17. Measuring error.qmd
    - 18. Missing data.qmd
    - 19. Modeling Network.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



