project:
  type: website
  

execute:
  startup: _setup.py

#execute: false

website:
  title: "Bayesian Inference (BI)"
  repo-url: https://github.com/BGN-for-ASNA/BI
  navbar:
    left:
      - href: start/Installation.qmd
        text: Get started
      - href: 0. Introduction.qmd
        text: Models
      - href: api_dist.qmd
        text: API Reference
      - text: Help
        menu:
            - text: Report a Bug
              icon: bug 
              href:  https://github.com/BGN-for-ASNA/BI/issues
            - text: Ask a Question
              icon: chat-dots 
              href:  https://github.com/BGN-for-ASNA/BI/discussions
    background: primary

    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        href:  https://github.com/BGN-for-ASNA/BI

  sidebar:
    #- border: true 
    - title: "Models"
      collapse-level: 1
      contents:      
        - 0. Introduction.qmd
        - 1. Linear Regression for continuous variable.qmd
        - 2. Multiple continuous Variables.qmd
        - 3. Interaction between continuous variables.qmd
        - 4. Categorical variable.qmd
        - 5. Binomial model.qmd
        - 6. Beta binomial model.qmd
        - 7. Poisson model.qmd
        - 8. Poisson mode with offset.qmd
        - 8. Gamma-Poisson.qmd
        - 9. Categorical model.qmd
        - 10. Multinomial model (wip).qmd
        - 10. Dirichlet model (wip).qmd
        - 11. Zero inflated.qmd
        - 12. Survival analysis.qmd
        - 13. Varying intercepts.qmd
        - 14. Varying slopes.qmd
        - 15. Gaussian processes.qmd
        - 16. Measuring error.qmd
        - 17. Missing data (wip).qmd
        - 18. Latent variable (wip).qmd
        - 19. PCA.qmd
        - 20. GMM.qmd
        - 21. DPMM.qmd
        - 22. Network model.qmd
        - 23. Network with block model.qmd
        - 24. Network control for data collection biases (wip).qmd
        - 25. Network Metrics.qmd
        - 26. Network Based Diffusion analysis (wip).qmd
        - 27. BNN.qmd

    - id: api
      title: "API Reference"
      contents:
        - api_manip.qmd              
        - api_dist.qmd
        - api_diag.qmd

    - id: start
      collapse-level: 2
      title: "Get started"
      contents:
        - section: "Installation"
          contents:
            - start/Installation.qmd     
        - section: "Pipeline"
          contents:        
            - start/Import_class.qmd
            - start/Import_data.qmd
            - start/Define model.qmd
            - start/Fit model.qmd
            - start/Diagnostics.qmd
        - section: "Advance"
          contents:
            - Advance/build in functions.qmd
            - Advance/Build in models.qmd

  page-navigation: true
  

format:
  html:
    theme:       
      dark: solar
      light: Morph
    css: MyStyles.css
    code-copy: true
    highlight-style: monokai
    toc: true
    toc-location: right
    html-math-method: katex
    grid:
      body-width: 1000px
    code-fold: false
    code-overflow: wrap
    code-tools: false
    include-after-body: [tooltip-scripts.html,disable-codefold.html]

  pdf:
    pdf-engine: xelatex
    #keep-tex: true
    header-includes:
      - \usepackage{amsmath} # amsmath is better than unicode-math for cases
      - \usepackage{amssymb}


bibliography: references.bib


